 # ref: https://docs.codecov.com/docs/codecovyml-reference

coverage:
  range: 40..92
  round: down
  precision: 2
  # status: See https://docs.codecov.com/docs/commit-status
  status:
    project:
      default:
        target: auto
        threshold: 1% # Allow coverage to drop by X%, posting a success status.
        # removed_code_behavior: Takes values [off, removals_only, adjust_base]
        removed_code_behavior: adjust_base
    patch:
      default:
        threshold: 7%

# See https://docs.codecov.com/docs/pull-request-comments
comment:
  layout: "files"
  behavior: default
  require_changes: true # if true: only post the comment if coverage changes
